export {
  NOTHING,
  deadLetterId,
  declById,
  emphasises,
  idOf,
  isActive,
  join,
  packageId,
  parseId,
  eventKey,
  readTrace,
  resolve,
  type EventKey,
  type Highlight,
  type Instant,
  type InstanceRef,
  type Interval,
  type Join,
  type ParsedId,
  type Selection,
  type SelectionId,
  type TraceEvent,
} from "./selection.js";
